sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
before_install: gem install bundler -v 1.16.4
script:
- bundle exec rake test
- bundle exec cucumber features
- bundle exec dmp about
- bundle exec dmp gen 6 -c
deploy:
  provider: rubygems
  api_key:
    secure: UxtyKAWhfNoVFF9Mf/LRs03uZTgeXP7i1/MOtk9BUIiX/4911l5xCJKPFxeLCK9LkcUQtc/i18YaOuFZTRxQw6Bab06HL6kcm9JRDrFbHNluWZ28r3uHaMXaUm8r1a6zSPKLNPpRRPKXBy+4cOAP/uLaJIXzCsCT/A+kdjGLyTbGYECeGv+jgRkzI99Wo746VYeK2vRJu5RrB2wV57CZFlQVdZ2T8BFO3Z2oG8I5o7IV4ZHK6HmowZmoqRq6Dp4YhnCIZQwtE80iwc1xNA23al5sli/7GNgyoGgCWonN7LfjInrJvSr+Cnroo72uDZs2ChiBlEqfG8leq/K0s1SQyuJXG4vY9FQMLWpnGro0T6n1eatwHw2vnpcoCC3EXfDYUR5C/eHuJ10R8zySeH1eTFG6a5Amu/ZA97UJIwCg5imbWa6wJnUZ+Zk1GB8Y0yUOMGymgmjoAnq8AIT89Js16UvY6zJP128L8ojNsYHXf+pxXj1bk81iaIUw42NjsFFbIF21uLJvsZg6Gd7lqyQcY0CrzqtC9CxCWsvJeXAado4PTA3YDeovZfGgpLHubYp1Ck0cIXVTyQw7mLYp+HoZpcUTH6eTfAbfdVivzCOkUe8bSrmg2LpBIA1zbLIPUtoCy0WrCa7952oa+6ofknbIMzpS7gFQ3F34vCQPwp4AORo=
  gem: dmp
  on:
    tags: true
    repo: franccesco/dmp
after_deploy:
- gem install dmp
- dmp gen 6 -c
- dmp about
notifications:
  slack:
    secure: eI+zyKfhWZ8nOzm+H5inaD1VoJVWWEqXHr2kK1T+sJdWL7Za9s+thi4VMsqTnqQSDfRoHk0ShOJxUK3qRgRs4eD+2k1xooJ4bAzrJso/y/pxWBAeoK87/tPk5tleE4XPUzX5oBnWQqITPfu+vOf1YU2F+BxvyUWQKjUCvdhD+nDsW+L0cP+VfnElcaaVoBK1dN5Is4fpbrga4U8OL9CwuB0zHBy5rUU+lO9cUr7Vz8B4mY3gIwMJCU51/qHZaPsKGOtpr7rAmMwUoERSVxREqmQXUy/43Um8UIcYiMxFXE+s381cND9iMmrXxZwaGX3FQ8eRQCRvkxFoMu56R4fupQkTe2QSpbgYM8Cfy6x8wc7th8DIF6Bd+6hWTy0l37IB/gVdk0ZvH8lq8T/NV85suqEGxegs/qxbijS5PgU3uOLoy7CGU/se9yew/Y/2wGBW6LHdPKlqZorlj+kxRbVsHKC4hwagzQL8H7p8BMnr7qxcqVhyP4e8DNScJXds++GN1BE8vjGx2wNjwxgpG7hQogx74/Y1DVzgnMu+x2k2I82QHdEUolFDArjAib453M56A1FZ+BKEF9GOOrwrdcdXcnpVayCP+5a7pHxAQENP/rWgnYiCnhOCVhBL1XjFvnG0RcjsOPUL9vzXHpScGq8lyI/MrtfTpRptojbd9+0JaUQ=
